import { chromium } from 'playwright';
import sharp from 'sharp';
import fs from 'node:fs';
import crypto from 'node:crypto';
const URL='https://infoworks-jp.github.io/tsubasa-official-site/';const OUT='verification-artifacts';fs.mkdirSync(OUT,{recursive:true});const sleep=ms=>new Promise(r=>setTimeout(r,ms));const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const critical=['index.html','assets/ramen-user.jpg','assets/food/limited.webp','assets/store-interior.png','assets/logo-horizontal.jpg','assets/menu/menu-ja.svg','assets/menu/menu-en.svg'];
async function publicMatchesRepo(){for(const p of critical){const local=fs.readFileSync(p);try{const r=await fetch(URL+p+'?fresh='+Date.now(),{cache:'no-store',signal:AbortSignal.timeout(10000)});if(!r.ok)return false;const remote=Buffer.from(await r.arrayBuffer());if(sha(local)!==sha(remote))return false;}catch{return false;}}return true;}
let deployed=false;for(let i=0;i<36;i++){if(await publicMatchesRepo()){deployed=true;break;}await sleep(5000);}if(!deployed)throw Error('deploy timeout: public files do not match repository');
const browser=await chromium.launch({headless:true});const errors=[];
async function pixelDiff(a,b){const A=await sharp(a).removeAlpha().raw().toBuffer({resolveWithObject:true}),B=await sharp(b).removeAlpha().raw().toBuffer({resolveWithObject:true});if(A.info.width!==B.info.width||A.info.height!==B.info.height)return{ratio:1};let changed=0,total=A.data.length/3;for(let i=0;i<A.data.length;i+=3){const d=Math.abs(A.data[i]-B.data[i])+Math.abs(A.data[i+1]-B.data[i+1])+Math.abs(A.data[i+2]-B.data[i+2]);if(d>18)changed++;}return{ratio:changed/total,changed,total};}
async function verifyViewport(width,height,name){const ctx=await browser.newContext({viewport:{width,height},deviceScaleFactor:1,reducedMotion:'no-preference'});const page=await ctx.newPage();const responses=[];page.on('console',m=>{if(m.type()==='error')errors.push(`${name}: ${m.text()}`)});page.on('pageerror',e=>errors.push(`${name}: ${String(e)}`));page.on('response',r=>{if(r.status()>=400)responses.push(`${r.status()} ${r.url()}`)});await page.goto(URL+'?verify='+Date.now(),{waitUntil:'networkidle',timeout:40000});await page.waitForSelector('#stage',{state:'visible',timeout:10000});await page.waitForSelector('.liquidTitle',{state:'visible',timeout:10000});await page.waitForTimeout(600);
const files=[];const states=[];async function snap(label){const s=await page.evaluate(()=>{const stage=document.querySelector('#stage'),title=document.querySelector('.liquidTitle'),photo=document.querySelector('.photo'),reveal=document.querySelector('.reveal'),store=document.querySelector('.storeBg'),particle=document.querySelector('#particles'),menu=document.querySelector('#menuImage');return{scrollY,stageRect:stage.getBoundingClientRect().toJSON(),titleRect:title.getBoundingClientRect().toJSON(),photoImage:getComputedStyle(photo).backgroundImage,revealImage:getComputedStyle(reveal).backgroundImage,revealVar:getComputedStyle(stage).getPropertyValue('--reveal').trim(),brandOpacity:getComputedStyle(stage).getPropertyValue('--brandOpacity').trim(),particleSize:[particle.width,particle.height],storeImage:getComputedStyle(store).backgroundImage,menuSrc:menu?.getAttribute('src')||'',images:[...document.images].map(i=>({src:i.currentSrc||i.src,ok:i.complete&&i.naturalWidth>0})),overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth+1};});const f=`${OUT}/${name}-${label}.png`;await page.screenshot({path:f,fullPage:false});files.push(f);states.push({label,...s});}
await snap('0s');const tr=await page.locator('.liquidTitle').boundingBox();if(tr){await page.mouse.move(tr.x+tr.width*.5,tr.y+tr.height*.5);await page.mouse.move(tr.x+tr.width*.78,tr.y+tr.height*.35,{steps:12});}await page.waitForTimeout(1000);await snap('pointer');const heroH=await page.locator('.hero').evaluate(el=>el.offsetHeight);await page.evaluate(y=>scrollTo(0,y),Math.max(1,heroH*0.34));await page.waitForTimeout(900);await snap('reveal');await page.evaluate(y=>scrollTo(0,y),Math.max(1,heroH*0.66));await page.waitForTimeout(1000);await snap('particles');await page.evaluate(()=>document.querySelector('[data-menu="en"]')?.click());await page.waitForTimeout(400);const menuEN=await page.evaluate(()=>({src:document.querySelector('#menuImage')?.getAttribute('src')||'',ok:document.querySelector('#menuImage')?.complete&&document.querySelector('#menuImage')?.naturalWidth>0}));const diffs={pointer:await pixelDiff(files[0],files[1]),reveal:await pixelDiff(files[1],files[2]),particles:await pixelDiff(files[2],files[3])};const pass=!states.some(s=>s.overflow)&&states.every(s=>s.images.every(i=>i.ok))&&states.every(s=>s.photoImage.includes('ramen-user.jpg'))&&states.every(s=>s.revealImage.includes('limited.webp'))&&states.every(s=>s.storeImage.includes('store-interior.png'))&&states.every(s=>s.particleSize[0]>0&&s.particleSize[1]>0)&&parseFloat(states[2].revealVar)>20&&parseFloat(states[3].revealVar)>parseFloat(states[2].revealVar)&&diffs.pointer.ratio>.0002&&diffs.reveal.ratio>.02&&diffs.particles.ratio>.005&&menuEN.src.includes('menu-en.svg')&&menuEN.ok&&!responses.length;
const result={pass,width,height,responses,states,diffs,menuEN};fs.writeFileSync(`${OUT}/${name}.json`,JSON.stringify(result,null,2));await ctx.close();return result;}
try{const desktop=await verifyViewport(1440,1000,'desktop-1440');const mobile=await verifyViewport(390,844,'mobile-390');const pass=desktop.pass&&mobile.pass&&!errors.length;fs.writeFileSync(`${OUT}/verification.json`,JSON.stringify({pass,errors,desktop,mobile},null,2));if(!pass)process.exitCode=1;}finally{await browser.close();}
